version: '3.8'

services:
  # 1. Hạ tầng Cơ sở dữ liệu PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: daily-vocab-postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: daily_vocab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret # Thay bằng mật khẩu thật của bạn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 2. Ứng dụng Backend Spring Boot
  spring-backend:
    build: .
    container_name: daily-vocab-backend
    ports:
      - "8080:8080"
    environment:
      # Thay đổi đường dẫn kết nối URL qua tên service của Container thay vì localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/daily_vocab_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      RAPIDAPI_KEY: 9201ab90a8mshd72806d7e973316p1dc4b3jsn46d75e96d052
    depends_on:
      - postgres-db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge