    spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/daily_vocab
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

rapidapi.key=${RAPIDAPI_KEY}